// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW_icR3If_t-8UfvkocynxV5ZC4xChRDA',
    appId: '1:45892551158:web:4f89856ee81b62539f47d7',
    messagingSenderId: '45892551158',
    projectId: 'todoapp-fd5e5',
    authDomain: 'todoapp-fd5e5.firebaseapp.com',
    storageBucket: 'todoapp-fd5e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ioNRbQTducYPtPLMlv3RBFJJGmXtg_4',
    appId: '1:45892551158:android:29cf9f805d97b2f59f47d7',
    messagingSenderId: '45892551158',
    projectId: 'todoapp-fd5e5',
    storageBucket: 'todoapp-fd5e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBblhweX4WW6yCwAQ5KScpcJRbOeenOs8A',
    appId: '1:45892551158:ios:9e02516f76b1cded9f47d7',
    messagingSenderId: '45892551158',
    projectId: 'todoapp-fd5e5',
    storageBucket: 'todoapp-fd5e5.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBblhweX4WW6yCwAQ5KScpcJRbOeenOs8A',
    appId: '1:45892551158:ios:9e02516f76b1cded9f47d7',
    messagingSenderId: '45892551158',
    projectId: 'todoapp-fd5e5',
    storageBucket: 'todoapp-fd5e5.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW_icR3If_t-8UfvkocynxV5ZC4xChRDA',
    appId: '1:45892551158:web:d61331f8698dc8259f47d7',
    messagingSenderId: '45892551158',
    projectId: 'todoapp-fd5e5',
    authDomain: 'todoapp-fd5e5.firebaseapp.com',
    storageBucket: 'todoapp-fd5e5.firebasestorage.app',
  );

}